/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Frames = number;
export type Url = string;
export type Jobid = string;
export type Kind = string;
export type Direction = "up" | "down" | "left" | "right" | "in" | "out" | "reset";
export type Distance = number;
export type Focallength = number;
export type Groundnear = number | null;
export type Horizonrow = number | null;
export type Maxdistance = number;
export type Pitch = number | null;
export type Distance1 = number;
export type Focallength1 = number;
export type Groundnear1 = number;
export type Horizonrow1 = number | null;
export type Maxdistance1 = number;
export type Pitch1 = number;
export type Model = string;
export type Code = string;
export type Message = string;
export type Dof = boolean;
export type Ok = boolean;
export type Version = string;
export type Height = number;
export type Width = number;
export type Generationid = string;
export type Generationid1 = string;
export type Images = AssetRef[];
export type Sliceindex = number;
export type Mode = "paint" | "fill" | "enhance";
export type Negativeprompt = string;
export type Positiveprompt = string;
export type Negativeprompt1 = string;
export type Positiveprompt1 = string;
export type Candidate = number | null;
export type Generationid2 = string;
export type Apikey = string | null;
export type Blur = number | null;
export type Externalserver = string | null;
export type Guidancescale = number | null;
export type Model1 = string | null;
export type Padding = number | null;
export type Strength = number | null;
export type Blur1 = number;
export type Externalserver1 = string;
export type Guidancescale1 = number;
export type Hasworkflow = boolean;
export type Model2 = string;
export type Padding1 = number;
export type Selectedcandidate = number | null;
export type Strength1 = number;
export type Error = string | null;
export type Id = string;
export type Kind1 = string;
export type Progress = number;
export type Clipboard = boolean;
export type Depthmodel = string;
export type Upscaled = boolean;
export type Id1 = string;
export type Numslices = number;
export type Revision = number;
export type Cameraz = number;
export type Bottom = number;
export type Index = number;
export type Top = number;
export type Z = number;
export type Cards = ProfileCardView[];
export type Backdroptop = number | null;
export type Farz = number;
export type Height1 = number;
export type Nearz = number;
export type Halffov = number;
export type Pitch2 = number;
export type Hasmask = boolean;
export type Multipointmode = boolean;
export type Negative = boolean;
export type X = number;
export type Y = number;
export type Queuedpoints = SegmentationPoint[];
export type Slicepixel = [unknown, unknown] | null;
export type Slicepixeldepth = number | null;
export type Selectedslice = number | null;
export type Darkmode = boolean;
export type Depthmodel1 = string;
export type Meshdisplacement = number;
export type Canredo = boolean;
export type Canundo = boolean;
export type Depth = number;
export type Index1 = number;
export type Isground = boolean;
export type Negativeprompt2 = string;
export type Positiveprompt2 = string;
export type Version1 = number;
export type Slices = SliceView[];
export type Thresholds = number[];
export type Usecheckerboard = boolean;
export type Status = "queued" | "running" | "succeeded" | "failed";
export type Level = string;
export type Message1 = string;
export type Seq = number;
export type Entries = LogEntryView[];
export type Next = number;
export type Enabled = boolean;
export type Message2 = string;
export type Ok1 = boolean;
export type Model3 = string;
export type Serveraddress = string;
export type Darkmode1 = boolean | null;
export type Depthmodel2 = string | null;
export type Meshdisplacement1 = number | null;
export type Ctrlkey = boolean;
export type Mode1 = "depth" | "instance";
export type Shiftkey = boolean;
export type X1 = number;
export type Y1 = number;
export type Slice = number | null;
export type Usecheckerboard1 = boolean;
export type Isground1 = boolean;
export type Depth1 = number;
export type Numslices1 = number;
export type Baserevision = number;
export type Values = number[];
export type Apikey1 = string;
export type Model4 = string;

export interface ParallaxMakerApi {
  [k: string]: unknown;
}
/**
 * Body of ``POST /projects/{id}/export/animation``.
 *
 * This interface was referenced by `ParallaxMakerApi`'s JSON-Schema
 * via the `definition` "AnimationExportRequest".
 */
export interface AnimationExportRequest {
  frames: Frames;
}
/**
 * A fetchable asset URL; opaque to clients beyond ``fetch``-ing it.
 *
 * This interface was referenced by `ParallaxMakerApi`'s JSON-Schema
 * via the `definition` "AssetRef".
 */
export interface AssetRef {
  url: Url;
}
/**
 * This interface was referenced by `ParallaxMakerApi`'s JSON-Schema
 * via the `definition` "BusyView".
 */
export interface BusyView {
  jobId: Jobid;
  kind: Kind;
}
/**
 * Body of ``POST /projects/{id}/camera/navigate``.
 *
 * Mirrors the seven ``NAV_*`` buttons of the removed Dash
 * ``navigate_image`` callback (see ``camera_services.py``): six unit steps
 * plus ``reset``, which snaps the camera back to
 * ``[0, 0, -camera_distance]``.
 *
 * This interface was referenced by `ParallaxMakerApi`'s JSON-Schema
 * via the `definition` "CameraNavigateRequest".
 */
export interface CameraNavigateRequest {
  direction: Direction;
}
/**
 * The nested ``camera`` object of ``PUT .../settings``; all three fields
 * are required together (a client that wants to change one camera value
 * sends the whole triple, matching Dash's own sliders, which always submit
 * distance/focal length/max distance together).
 *
 * This interface was referenced by `ParallaxMakerApi`'s JSON-Schema
 * via the `definition` "CameraSettingsRequest".
 */
export interface CameraSettingsRequest {
  distance: Distance;
  focalLength: Focallength;
  groundNear?: Groundnear;
  horizonRow?: Horizonrow;
  maxDistance: Maxdistance;
  pitch?: Pitch;
}
/**
 * This interface was referenced by `ParallaxMakerApi`'s JSON-Schema
 * via the `definition` "CameraSettingsView".
 */
export interface CameraSettingsView {
  distance: Distance1;
  focalLength: Focallength1;
  groundNear?: Groundnear1;
  horizonRow?: Horizonrow1;
  maxDistance: Maxdistance1;
  pitch?: Pitch1;
}
/**
 * This interface was referenced by `ParallaxMakerApi`'s JSON-Schema
 * via the `definition` "DepthRequest".
 */
export interface DepthRequest {
  model: Model;
}
/**
 * This interface was referenced by `ParallaxMakerApi`'s JSON-Schema
 * via the `definition` "ErrorBody".
 */
export interface ErrorBody {
  error: ErrorDetail;
}
/**
 * This interface was referenced by `ParallaxMakerApi`'s JSON-Schema
 * via the `definition` "ErrorDetail".
 */
export interface ErrorDetail {
  code: Code;
  message: Message;
}
/**
 * Body of ``POST /projects/{id}/export/gltf``.
 *
 * This interface was referenced by `ParallaxMakerApi`'s JSON-Schema
 * via the `definition` "GltfExportRequest".
 */
export interface GltfExportRequest {
  dof?: Dof;
}
/**
 * This interface was referenced by `ParallaxMakerApi`'s JSON-Schema
 * via the `definition` "HealthView".
 */
export interface HealthView {
  ok: Ok;
  version: Version;
}
/**
 * This interface was referenced by `ParallaxMakerApi`'s JSON-Schema
 * via the `definition` "ImageSize".
 */
export interface ImageSize {
  height: Height;
  width: Width;
}
/**
 * Body of ``POST .../slices/{index}/inpainting/apply``.
 *
 * This interface was referenced by `ParallaxMakerApi`'s JSON-Schema
 * via the `definition` "InpaintingApplyRequest".
 */
export interface InpaintingApplyRequest {
  generationId: Generationid;
}
/**
 * One server-held candidate generation; see the "Candidates" section of
 * ``docs/svelte-migration/ARCHITECTURE.md``.
 *
 * This interface was referenced by `ParallaxMakerApi`'s JSON-Schema
 * via the `definition` "InpaintingCandidatesView".
 */
export interface InpaintingCandidatesView {
  generationId: Generationid1;
  images: Images;
  sliceIndex: Sliceindex;
}
/**
 * Body of ``POST .../slices/{index}/inpainting/generate``.
 *
 * This interface was referenced by `ParallaxMakerApi`'s JSON-Schema
 * via the `definition` "InpaintingGenerateRequest".
 */
export interface InpaintingGenerateRequest {
  mode: Mode;
  negativePrompt?: Negativeprompt;
  positivePrompt?: Positiveprompt;
}
/**
 * Body of ``PUT .../slices/{index}/prompts``.
 *
 * This interface was referenced by `ParallaxMakerApi`'s JSON-Schema
 * via the `definition` "InpaintingPromptsRequest".
 */
export interface InpaintingPromptsRequest {
  negativePrompt?: Negativeprompt1;
  positivePrompt?: Positiveprompt1;
}
/**
 * Body of ``PUT /projects/{id}/inpainting/selection``.
 *
 * ``candidate=None`` clears the selection; selecting the same index again
 * toggles it off (``InpaintingService.select_candidate``'s own contract).
 *
 * This interface was referenced by `ParallaxMakerApi`'s JSON-Schema
 * via the `definition` "InpaintingSelectionRequest".
 */
export interface InpaintingSelectionRequest {
  candidate: Candidate;
  generationId: Generationid2;
}
/**
 * Body of ``PUT /projects/{id}/inpainting/settings``.
 *
 * Every field is optional so a client can update just one setting; only
 * fields actually present in the request body are applied (see
 * ``model_fields_set``/``exclude_unset``). ``model`` is the only field
 * ``InpaintingService.update_model`` itself understands - the rest become
 * project-level defaults consumed by the next
 * ``POST .../inpainting/generate`` (see the "Candidates" section of
 * ``docs/svelte-migration/ARCHITECTURE.md``); ``externalServer``/``apiKey``
 * are additionally written onto ``AppState`` the same way Dash's own
 * settings panel does. ``apiKey`` is write-only: it is never echoed back.
 *
 * This interface was referenced by `ParallaxMakerApi`'s JSON-Schema
 * via the `definition` "InpaintingSettingsRequest".
 */
export interface InpaintingSettingsRequest {
  apiKey?: Apikey;
  blur?: Blur;
  externalServer?: Externalserver;
  guidanceScale?: Guidancescale;
  model?: Model1;
  padding?: Padding;
  strength?: Strength;
}
/**
 * Inpainting model/parameter settings and the current candidate set.
 *
 * Never carries ``apiKey`` or any other credential; see
 * ``runtime.InpaintingSettings``/``api/inpainting.py``.
 *
 * This interface was referenced by `ParallaxMakerApi`'s JSON-Schema
 * via the `definition` "InpaintingView".
 */
export interface InpaintingView {
  blur: Blur1;
  candidates?: InpaintingCandidatesView | null;
  externalServer: Externalserver1;
  guidanceScale: Guidancescale1;
  hasWorkflow: Hasworkflow;
  model: Model2;
  padding: Padding1;
  selectedCandidate?: Selectedcandidate;
  strength: Strength1;
}
/**
 * The ``{job}`` envelope returned by ``202`` job-creation responses.
 *
 * This interface was referenced by `ParallaxMakerApi`'s JSON-Schema
 * via the `definition` "JobRef".
 */
export interface JobRef {
  job: JobView;
}
/**
 * This interface was referenced by `ParallaxMakerApi`'s JSON-Schema
 * via the `definition` "JobView".
 */
export interface JobView {
  error?: Error;
  id: Id;
  kind: Kind1;
  progress: Progress;
  project?: ProjectView | null;
  status: Status;
}
/**
 * Public projection of ``AppState``; never serialize PIL/NumPy/credentials.
 *
 * This interface was referenced by `ParallaxMakerApi`'s JSON-Schema
 * via the `definition` "ProjectView".
 */
export interface ProjectView {
  assets: ProjectAssets;
  busy?: BusyView | null;
  clipboard?: Clipboard;
  depthModel: Depthmodel;
  exports: ProjectExportsView;
  id: Id1;
  image?: ImageSize | null;
  inpainting: InpaintingView;
  mainImage?: AssetRef | null;
  numSlices: Numslices;
  revision: Revision;
  sceneProfile?: SceneProfileView | null;
  segmentation: SegmentationView;
  selectedSlice?: Selectedslice;
  settings: ProjectSettingsView;
  slices: Slices;
  thresholds: Thresholds;
  useCheckerboard?: Usecheckerboard;
}
/**
 * This interface was referenced by `ParallaxMakerApi`'s JSON-Schema
 * via the `definition` "ProjectAssets".
 */
export interface ProjectAssets {
  depth?: AssetRef | null;
  input?: AssetRef | null;
}
/**
 * Content-versioned export availability (PARITY.md "Export/Render").
 *
 * This interface was referenced by `ParallaxMakerApi`'s JSON-Schema
 * via the `definition` "ProjectExportsView".
 */
export interface ProjectExportsView {
  gltf?: AssetRef | null;
  upscaled?: Upscaled;
}
/**
 * The scene seen from the side, for the UI's side view.
 *
 * World units, camera at ``(y=0, z=cameraZ)``; y points *down* (a card's
 * ``top`` is its smaller y). See ``ground_services.scene_profile``.
 *
 * This interface was referenced by `ParallaxMakerApi`'s JSON-Schema
 * via the `definition` "SceneProfileView".
 */
export interface SceneProfileView {
  cameraZ: Cameraz;
  cards: Cards;
  ground?: ProfileGroundView | null;
  halfFov: Halffov;
  pitch: Pitch2;
}
/**
 * This interface was referenced by `ParallaxMakerApi`'s JSON-Schema
 * via the `definition` "ProfileCardView".
 */
export interface ProfileCardView {
  bottom: Bottom;
  index: Index;
  top: Top;
  z: Z;
}
/**
 * This interface was referenced by `ParallaxMakerApi`'s JSON-Schema
 * via the `definition` "ProfileGroundView".
 */
export interface ProfileGroundView {
  backdropTop?: Backdroptop;
  farZ: Farz;
  height: Height1;
  nearZ: Nearz;
}
/**
 * Interaction state owned by ``SegmentationService``/``AppState``.
 *
 * This interface was referenced by `ParallaxMakerApi`'s JSON-Schema
 * via the `definition` "SegmentationView".
 */
export interface SegmentationView {
  hasMask: Hasmask;
  multiPointMode: Multipointmode;
  queuedPoints: Queuedpoints;
  slicePixel?: Slicepixel;
  slicePixelDepth?: Slicepixeldepth;
}
/**
 * One queued multi-point click; ``negative`` mirrors ``PointPolarity``.
 *
 * This interface was referenced by `ParallaxMakerApi`'s JSON-Schema
 * via the `definition` "SegmentationPoint".
 */
export interface SegmentationPoint {
  negative: Negative;
  x: X;
  y: Y;
}
/**
 * Persisted project-lifecycle/configuration settings (``PUT .../settings``).
 *
 * ``depth_model`` here is ``AppState.depth_model_name`` - the *persisted*
 * depth-model dropdown selection (``remember_depth_model``'s own value) -
 * which is a different concept from ``ProjectView.depth_model`` above
 * (``state.depth_estimation_model.model_name``, the model instance actually
 * used for the last depth generation; not restored from JSON, see
 * ``test_api_restore.py``). Both are kept: the top-level field's existing
 * contract is unchanged, and this one is what "configuration persistence"
 * (PARITY.md's WEB-29/WEB-30/WEB-38 rows) needs to expose.
 *
 * This interface was referenced by `ParallaxMakerApi`'s JSON-Schema
 * via the `definition` "ProjectSettingsView".
 */
export interface ProjectSettingsView {
  camera: CameraSettingsView;
  darkMode: Darkmode;
  depthModel: Depthmodel1;
  meshDisplacement: Meshdisplacement;
}
/**
 * This interface was referenced by `ParallaxMakerApi`'s JSON-Schema
 * via the `definition` "SliceView".
 */
export interface SliceView {
  canRedo: Canredo;
  canUndo: Canundo;
  depth: Depth;
  image: AssetRef;
  index: Index1;
  isGround?: Isground;
  mask?: AssetRef | null;
  negativePrompt: Negativeprompt2;
  positivePrompt: Positiveprompt2;
  thumbnail: AssetRef;
  version: Version1;
}
/**
 * This interface was referenced by `ParallaxMakerApi`'s JSON-Schema
 * via the `definition` "LogEntryView".
 */
export interface LogEntryView {
  level: Level;
  message: Message1;
  seq: Seq;
}
/**
 * This interface was referenced by `ParallaxMakerApi`'s JSON-Schema
 * via the `definition` "LogsView".
 */
export interface LogsView {
  entries: Entries;
  next: Next;
}
/**
 * This interface was referenced by `ParallaxMakerApi`'s JSON-Schema
 * via the `definition` "MultiPointRequest".
 */
export interface MultiPointRequest {
  enabled: Enabled;
}
/**
 * Response of both configuration-probe routes; ``message`` mirrors
 * Dash's own log line and never contains the tested credential.
 *
 * This interface was referenced by `ParallaxMakerApi`'s JSON-Schema
 * via the `definition` "ProbeResultView".
 */
export interface ProbeResultView {
  message: Message2;
  ok: Ok1;
}
/**
 * Body of ``POST /api/v1/config/probe-server``.
 *
 * This interface was referenced by `ParallaxMakerApi`'s JSON-Schema
 * via the `definition` "ProbeServerRequest".
 */
export interface ProbeServerRequest {
  model: Model3;
  serverAddress: Serveraddress;
}
/**
 * Body of ``PUT /projects/{id}/settings``.
 *
 * Every top-level field is optional so a client can update just one
 * setting; a field is only applied (and only counted toward ``changed``)
 * when both present *and* different from the project's current value - see
 * ``project_services.UpdateSettings``.
 *
 * This interface was referenced by `ParallaxMakerApi`'s JSON-Schema
 * via the `definition` "ProjectSettingsRequest".
 */
export interface ProjectSettingsRequest {
  camera?: CameraSettingsRequest | null;
  darkMode?: Darkmode1;
  depthModel?: Depthmodel2;
  meshDisplacement?: Meshdisplacement1;
}
/**
 * Body of ``POST .../segmentation/click``.
 *
 * ``x``/``y`` are integer source-image pixel coordinates (the client
 * performs Dash's ``find_pixel_from_click`` truncation); ``shiftKey``/
 * ``ctrlKey`` mirror the browser click event's modifier keys exactly like
 * Dash's ``click_event``.
 *
 * This interface was referenced by `ParallaxMakerApi`'s JSON-Schema
 * via the `definition` "SegmentationClickRequest".
 */
export interface SegmentationClickRequest {
  ctrlKey: Ctrlkey;
  mode: Mode1;
  shiftKey: Shiftkey;
  x: X1;
  y: Y1;
}
/**
 * Body of ``PUT .../selection``; ``slice=None`` deselects.
 *
 * This interface was referenced by `ParallaxMakerApi`'s JSON-Schema
 * via the `definition` "SelectionRequest".
 */
export interface SelectionRequest {
  slice: Slice;
}
/**
 * This interface was referenced by `ParallaxMakerApi`'s JSON-Schema
 * via the `definition` "SetCheckerboardRequest".
 */
export interface SetCheckerboardRequest {
  useCheckerboard: Usecheckerboard1;
}
/**
 * Body of ``PUT /projects/{id}/slices/{index}/ground``.
 *
 * This interface was referenced by `ParallaxMakerApi`'s JSON-Schema
 * via the `definition` "SetGroundPlaneRequest".
 */
export interface SetGroundPlaneRequest {
  isGround: Isground1;
}
/**
 * This interface was referenced by `ParallaxMakerApi`'s JSON-Schema
 * via the `definition` "SetSliceDepthRequest".
 */
export interface SetSliceDepthRequest {
  depth: Depth1;
}
/**
 * This interface was referenced by `ParallaxMakerApi`'s JSON-Schema
 * via the `definition` "SliceCountRequest".
 */
export interface SliceCountRequest {
  numSlices: Numslices1;
}
/**
 * This interface was referenced by `ParallaxMakerApi`'s JSON-Schema
 * via the `definition` "ThresholdsRequest".
 */
export interface ThresholdsRequest {
  baseRevision: Baserevision;
  values: Values;
}
/**
 * Body of ``POST /api/v1/config/validate-key``. ``api_key`` is
 * write-only: it is used for exactly one probe request and never stored or
 * echoed back.
 *
 * This interface was referenced by `ParallaxMakerApi`'s JSON-Schema
 * via the `definition` "ValidateKeyRequest".
 */
export interface ValidateKeyRequest {
  apiKey: Apikey1;
  model: Model4;
}
