/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Url = string;
export type Jobid = string;
export type Kind = string;
export type Model = string;
export type Code = string;
export type Message = string;
export type Ok = boolean;
export type Version = string;
export type Height = number;
export type Width = number;
export type Error = string | null;
export type Id = string;
export type Kind1 = string;
export type Progress = number;
export type Depthmodel = string;
export type Id1 = string;
export type Numslices = number;
export type Revision = number;
export type Selectedslice = number | null;
export type Canredo = boolean;
export type Canundo = boolean;
export type Depth = number;
export type Index = number;
export type Negativeprompt = string;
export type Positiveprompt = string;
export type Version1 = number;
export type Slices = SliceView[];
export type Thresholds = number[];
export type Status = "queued" | "running" | "succeeded" | "failed";
export type Level = string;
export type Message1 = string;
export type Seq = number;
export type Entries = LogEntryView[];
export type Next = number;
export type Numslices1 = number;
export type Baserevision = number;
export type Values = number[];

export interface ParallaxMakerApi {
  [k: string]: unknown;
}
/**
 * A fetchable asset URL; opaque to clients beyond ``fetch``-ing it.
 *
 * This interface was referenced by `ParallaxMakerApi`'s JSON-Schema
 * via the `definition` "AssetRef".
 */
export interface AssetRef {
  url: Url;
}
/**
 * This interface was referenced by `ParallaxMakerApi`'s JSON-Schema
 * via the `definition` "BusyView".
 */
export interface BusyView {
  jobId: Jobid;
  kind: Kind;
}
/**
 * This interface was referenced by `ParallaxMakerApi`'s JSON-Schema
 * via the `definition` "DepthRequest".
 */
export interface DepthRequest {
  model: Model;
}
/**
 * This interface was referenced by `ParallaxMakerApi`'s JSON-Schema
 * via the `definition` "ErrorBody".
 */
export interface ErrorBody {
  error: ErrorDetail;
}
/**
 * This interface was referenced by `ParallaxMakerApi`'s JSON-Schema
 * via the `definition` "ErrorDetail".
 */
export interface ErrorDetail {
  code: Code;
  message: Message;
}
/**
 * This interface was referenced by `ParallaxMakerApi`'s JSON-Schema
 * via the `definition` "HealthView".
 */
export interface HealthView {
  ok: Ok;
  version: Version;
}
/**
 * This interface was referenced by `ParallaxMakerApi`'s JSON-Schema
 * via the `definition` "ImageSize".
 */
export interface ImageSize {
  height: Height;
  width: Width;
}
/**
 * The ``{job}`` envelope returned by ``202`` job-creation responses.
 *
 * This interface was referenced by `ParallaxMakerApi`'s JSON-Schema
 * via the `definition` "JobRef".
 */
export interface JobRef {
  job: JobView;
}
/**
 * This interface was referenced by `ParallaxMakerApi`'s JSON-Schema
 * via the `definition` "JobView".
 */
export interface JobView {
  error?: Error;
  id: Id;
  kind: Kind1;
  progress: Progress;
  project?: ProjectView | null;
  status: Status;
}
/**
 * Public projection of ``AppState``; never serialize PIL/NumPy/credentials.
 *
 * This interface was referenced by `ParallaxMakerApi`'s JSON-Schema
 * via the `definition` "ProjectView".
 */
export interface ProjectView {
  assets: ProjectAssets;
  busy?: BusyView | null;
  depthModel: Depthmodel;
  id: Id1;
  image?: ImageSize | null;
  numSlices: Numslices;
  revision: Revision;
  selectedSlice?: Selectedslice;
  slices: Slices;
  thresholds: Thresholds;
}
/**
 * This interface was referenced by `ParallaxMakerApi`'s JSON-Schema
 * via the `definition` "ProjectAssets".
 */
export interface ProjectAssets {
  depth?: AssetRef | null;
  input?: AssetRef | null;
}
/**
 * This interface was referenced by `ParallaxMakerApi`'s JSON-Schema
 * via the `definition` "SliceView".
 */
export interface SliceView {
  canRedo: Canredo;
  canUndo: Canundo;
  depth: Depth;
  image: AssetRef;
  index: Index;
  negativePrompt: Negativeprompt;
  positivePrompt: Positiveprompt;
  thumbnail: AssetRef;
  version: Version1;
}
/**
 * This interface was referenced by `ParallaxMakerApi`'s JSON-Schema
 * via the `definition` "LogEntryView".
 */
export interface LogEntryView {
  level: Level;
  message: Message1;
  seq: Seq;
}
/**
 * This interface was referenced by `ParallaxMakerApi`'s JSON-Schema
 * via the `definition` "LogsView".
 */
export interface LogsView {
  entries: Entries;
  next: Next;
}
/**
 * This interface was referenced by `ParallaxMakerApi`'s JSON-Schema
 * via the `definition` "SliceCountRequest".
 */
export interface SliceCountRequest {
  numSlices: Numslices1;
}
/**
 * This interface was referenced by `ParallaxMakerApi`'s JSON-Schema
 * via the `definition` "ThresholdsRequest".
 */
export interface ThresholdsRequest {
  baseRevision: Baserevision;
  values: Values;
}
