/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Url = string;
export type Jobid = string;
export type Kind = string;
export type Model = string;
export type Code = string;
export type Message = string;
export type Ok = boolean;
export type Version = string;
export type Height = number;
export type Width = number;
export type Generationid = string;
export type Generationid1 = string;
export type Images = AssetRef[];
export type Sliceindex = number;
export type Mode = "paint" | "fill" | "enhance";
export type Negativeprompt = string;
export type Positiveprompt = string;
export type Negativeprompt1 = string;
export type Positiveprompt1 = string;
export type Candidate = number | null;
export type Generationid2 = string;
export type Apikey = string | null;
export type Blur = number | null;
export type Externalserver = string | null;
export type Guidancescale = number | null;
export type Model1 = string | null;
export type Padding = number | null;
export type Strength = number | null;
export type Blur1 = number;
export type Externalserver1 = string;
export type Guidancescale1 = number;
export type Hasworkflow = boolean;
export type Model2 = string;
export type Padding1 = number;
export type Selectedcandidate = number | null;
export type Strength1 = number;
export type Error = string | null;
export type Id = string;
export type Kind1 = string;
export type Progress = number;
export type Clipboard = boolean;
export type Depthmodel = string;
export type Id1 = string;
export type Numslices = number;
export type Revision = number;
export type Hasmask = boolean;
export type Multipointmode = boolean;
export type Negative = boolean;
export type X = number;
export type Y = number;
export type Queuedpoints = SegmentationPoint[];
export type Slicepixel = [unknown, unknown] | null;
export type Slicepixeldepth = number | null;
export type Selectedslice = number | null;
export type Canredo = boolean;
export type Canundo = boolean;
export type Depth = number;
export type Index = number;
export type Negativeprompt2 = string;
export type Positiveprompt2 = string;
export type Version1 = number;
export type Slices = SliceView[];
export type Thresholds = number[];
export type Usecheckerboard = boolean;
export type Status = "queued" | "running" | "succeeded" | "failed";
export type Level = string;
export type Message1 = string;
export type Seq = number;
export type Entries = LogEntryView[];
export type Next = number;
export type Enabled = boolean;
export type Ctrlkey = boolean;
export type Mode1 = "depth" | "instance";
export type Shiftkey = boolean;
export type X1 = number;
export type Y1 = number;
export type Slice = number | null;
export type Usecheckerboard1 = boolean;
export type Depth1 = number;
export type Numslices1 = number;
export type Baserevision = number;
export type Values = number[];

export interface ParallaxMakerApi {
  [k: string]: unknown;
}
/**
 * A fetchable asset URL; opaque to clients beyond ``fetch``-ing it.
 *
 * This interface was referenced by `ParallaxMakerApi`'s JSON-Schema
 * via the `definition` "AssetRef".
 */
export interface AssetRef {
  url: Url;
}
/**
 * This interface was referenced by `ParallaxMakerApi`'s JSON-Schema
 * via the `definition` "BusyView".
 */
export interface BusyView {
  jobId: Jobid;
  kind: Kind;
}
/**
 * This interface was referenced by `ParallaxMakerApi`'s JSON-Schema
 * via the `definition` "DepthRequest".
 */
export interface DepthRequest {
  model: Model;
}
/**
 * This interface was referenced by `ParallaxMakerApi`'s JSON-Schema
 * via the `definition` "ErrorBody".
 */
export interface ErrorBody {
  error: ErrorDetail;
}
/**
 * This interface was referenced by `ParallaxMakerApi`'s JSON-Schema
 * via the `definition` "ErrorDetail".
 */
export interface ErrorDetail {
  code: Code;
  message: Message;
}
/**
 * This interface was referenced by `ParallaxMakerApi`'s JSON-Schema
 * via the `definition` "HealthView".
 */
export interface HealthView {
  ok: Ok;
  version: Version;
}
/**
 * This interface was referenced by `ParallaxMakerApi`'s JSON-Schema
 * via the `definition` "ImageSize".
 */
export interface ImageSize {
  height: Height;
  width: Width;
}
/**
 * Body of ``POST .../slices/{index}/inpainting/apply``.
 *
 * This interface was referenced by `ParallaxMakerApi`'s JSON-Schema
 * via the `definition` "InpaintingApplyRequest".
 */
export interface InpaintingApplyRequest {
  generationId: Generationid;
}
/**
 * One server-held candidate generation; see the "Candidates" section of
 * ``docs/svelte-migration/ARCHITECTURE.md``.
 *
 * This interface was referenced by `ParallaxMakerApi`'s JSON-Schema
 * via the `definition` "InpaintingCandidatesView".
 */
export interface InpaintingCandidatesView {
  generationId: Generationid1;
  images: Images;
  sliceIndex: Sliceindex;
}
/**
 * Body of ``POST .../slices/{index}/inpainting/generate``.
 *
 * This interface was referenced by `ParallaxMakerApi`'s JSON-Schema
 * via the `definition` "InpaintingGenerateRequest".
 */
export interface InpaintingGenerateRequest {
  mode: Mode;
  negativePrompt?: Negativeprompt;
  positivePrompt?: Positiveprompt;
}
/**
 * Body of ``PUT .../slices/{index}/prompts``.
 *
 * This interface was referenced by `ParallaxMakerApi`'s JSON-Schema
 * via the `definition` "InpaintingPromptsRequest".
 */
export interface InpaintingPromptsRequest {
  negativePrompt?: Negativeprompt1;
  positivePrompt?: Positiveprompt1;
}
/**
 * Body of ``PUT /projects/{id}/inpainting/selection``.
 *
 * ``candidate=None`` clears the selection; selecting the same index again
 * toggles it off (``InpaintingService.select_candidate``'s own contract).
 *
 * This interface was referenced by `ParallaxMakerApi`'s JSON-Schema
 * via the `definition` "InpaintingSelectionRequest".
 */
export interface InpaintingSelectionRequest {
  candidate: Candidate;
  generationId: Generationid2;
}
/**
 * Body of ``PUT /projects/{id}/inpainting/settings``.
 *
 * Every field is optional so a client can update just one setting; only
 * fields actually present in the request body are applied (see
 * ``model_fields_set``/``exclude_unset``). ``model`` is the only field
 * ``InpaintingService.update_model`` itself understands - the rest become
 * project-level defaults consumed by the next
 * ``POST .../inpainting/generate`` (see the "Candidates" section of
 * ``docs/svelte-migration/ARCHITECTURE.md``); ``externalServer``/``apiKey``
 * are additionally written onto ``AppState`` the same way Dash's own
 * settings panel does. ``apiKey`` is write-only: it is never echoed back.
 *
 * This interface was referenced by `ParallaxMakerApi`'s JSON-Schema
 * via the `definition` "InpaintingSettingsRequest".
 */
export interface InpaintingSettingsRequest {
  apiKey?: Apikey;
  blur?: Blur;
  externalServer?: Externalserver;
  guidanceScale?: Guidancescale;
  model?: Model1;
  padding?: Padding;
  strength?: Strength;
}
/**
 * Inpainting model/parameter settings and the current candidate set.
 *
 * Never carries ``apiKey`` or any other credential; see
 * ``runtime.InpaintingSettings``/``api/inpainting.py``.
 *
 * This interface was referenced by `ParallaxMakerApi`'s JSON-Schema
 * via the `definition` "InpaintingView".
 */
export interface InpaintingView {
  blur: Blur1;
  candidates?: InpaintingCandidatesView | null;
  externalServer: Externalserver1;
  guidanceScale: Guidancescale1;
  hasWorkflow: Hasworkflow;
  model: Model2;
  padding: Padding1;
  selectedCandidate?: Selectedcandidate;
  strength: Strength1;
}
/**
 * The ``{job}`` envelope returned by ``202`` job-creation responses.
 *
 * This interface was referenced by `ParallaxMakerApi`'s JSON-Schema
 * via the `definition` "JobRef".
 */
export interface JobRef {
  job: JobView;
}
/**
 * This interface was referenced by `ParallaxMakerApi`'s JSON-Schema
 * via the `definition` "JobView".
 */
export interface JobView {
  error?: Error;
  id: Id;
  kind: Kind1;
  progress: Progress;
  project?: ProjectView | null;
  status: Status;
}
/**
 * Public projection of ``AppState``; never serialize PIL/NumPy/credentials.
 *
 * This interface was referenced by `ParallaxMakerApi`'s JSON-Schema
 * via the `definition` "ProjectView".
 */
export interface ProjectView {
  assets: ProjectAssets;
  busy?: BusyView | null;
  clipboard?: Clipboard;
  depthModel: Depthmodel;
  id: Id1;
  image?: ImageSize | null;
  inpainting: InpaintingView;
  mainImage?: AssetRef | null;
  numSlices: Numslices;
  revision: Revision;
  segmentation: SegmentationView;
  selectedSlice?: Selectedslice;
  slices: Slices;
  thresholds: Thresholds;
  useCheckerboard?: Usecheckerboard;
}
/**
 * This interface was referenced by `ParallaxMakerApi`'s JSON-Schema
 * via the `definition` "ProjectAssets".
 */
export interface ProjectAssets {
  depth?: AssetRef | null;
  input?: AssetRef | null;
}
/**
 * Interaction state owned by ``SegmentationService``/``AppState``.
 *
 * This interface was referenced by `ParallaxMakerApi`'s JSON-Schema
 * via the `definition` "SegmentationView".
 */
export interface SegmentationView {
  hasMask: Hasmask;
  multiPointMode: Multipointmode;
  queuedPoints: Queuedpoints;
  slicePixel?: Slicepixel;
  slicePixelDepth?: Slicepixeldepth;
}
/**
 * One queued multi-point click; ``negative`` mirrors ``PointPolarity``.
 *
 * This interface was referenced by `ParallaxMakerApi`'s JSON-Schema
 * via the `definition` "SegmentationPoint".
 */
export interface SegmentationPoint {
  negative: Negative;
  x: X;
  y: Y;
}
/**
 * This interface was referenced by `ParallaxMakerApi`'s JSON-Schema
 * via the `definition` "SliceView".
 */
export interface SliceView {
  canRedo: Canredo;
  canUndo: Canundo;
  depth: Depth;
  image: AssetRef;
  index: Index;
  mask?: AssetRef | null;
  negativePrompt: Negativeprompt2;
  positivePrompt: Positiveprompt2;
  thumbnail: AssetRef;
  version: Version1;
}
/**
 * This interface was referenced by `ParallaxMakerApi`'s JSON-Schema
 * via the `definition` "LogEntryView".
 */
export interface LogEntryView {
  level: Level;
  message: Message1;
  seq: Seq;
}
/**
 * This interface was referenced by `ParallaxMakerApi`'s JSON-Schema
 * via the `definition` "LogsView".
 */
export interface LogsView {
  entries: Entries;
  next: Next;
}
/**
 * This interface was referenced by `ParallaxMakerApi`'s JSON-Schema
 * via the `definition` "MultiPointRequest".
 */
export interface MultiPointRequest {
  enabled: Enabled;
}
/**
 * Body of ``POST .../segmentation/click``.
 *
 * ``x``/``y`` are integer source-image pixel coordinates (the client
 * performs Dash's ``find_pixel_from_click`` truncation); ``shiftKey``/
 * ``ctrlKey`` mirror the browser click event's modifier keys exactly like
 * Dash's ``click_event``.
 *
 * This interface was referenced by `ParallaxMakerApi`'s JSON-Schema
 * via the `definition` "SegmentationClickRequest".
 */
export interface SegmentationClickRequest {
  ctrlKey: Ctrlkey;
  mode: Mode1;
  shiftKey: Shiftkey;
  x: X1;
  y: Y1;
}
/**
 * Body of ``PUT .../selection``; ``slice=None`` deselects.
 *
 * This interface was referenced by `ParallaxMakerApi`'s JSON-Schema
 * via the `definition` "SelectionRequest".
 */
export interface SelectionRequest {
  slice: Slice;
}
/**
 * This interface was referenced by `ParallaxMakerApi`'s JSON-Schema
 * via the `definition` "SetCheckerboardRequest".
 */
export interface SetCheckerboardRequest {
  useCheckerboard: Usecheckerboard1;
}
/**
 * This interface was referenced by `ParallaxMakerApi`'s JSON-Schema
 * via the `definition` "SetSliceDepthRequest".
 */
export interface SetSliceDepthRequest {
  depth: Depth1;
}
/**
 * This interface was referenced by `ParallaxMakerApi`'s JSON-Schema
 * via the `definition` "SliceCountRequest".
 */
export interface SliceCountRequest {
  numSlices: Numslices1;
}
/**
 * This interface was referenced by `ParallaxMakerApi`'s JSON-Schema
 * via the `definition` "ThresholdsRequest".
 */
export interface ThresholdsRequest {
  baseRevision: Baserevision;
  values: Values;
}
